Shop.Web/Controllers/CartController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Shop.Domain.Entities.Shop;
using Shop.ServicesFacade.Base;
using Shop.ServicesFacade.Concrete.Shop;
using Shop.ViewModel.Shop;
using Constants = Shop.Web.Helpers.Constants;

namespace Shop.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService cartService;
        private readonly IService<Product> productService;

        public CartController(ICartService cartService, IService<Product> productService)
        {
            this.cartService = cartService;
            this.productService = productService;
        }

        [ChildActionOnly]
        public ActionResult Get()
        {
            var cart = Session[Constants.CartSessionKey] as CartViewModel;
            if (User.Identity.IsAuthenticated)
            {
                cart = GetCart();
            }

            return PartialView("_Cart", cart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddItem(int productId)
        {
            var product = await productService.GetAsync(productId);

            var cart = GetCart();
            cart = await cartService.AddToCart(cart, product, 1);

            Session[Constants.CartSessionKey] = cart;

            return PartialView("_Cart", cart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteItem(CartItemViewModel model)
        {
            var cart = GetCart();
            cart = await cartService.DeleteFromCart(cart, model);

            Session[Constants.CartSessionKey] = cart;

            return PartialView("_Cart", cart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Empty()
        {
            var cart = GetCart();
            await cartService.EmptyCart(cart);

            Session[Constants.CartSessionKey] = null;

            return PartialView("_Cart");
        }

        #region Private methods
        // Need to avoid async because it is used in child action
        private CartViewModel GetCart()
        {
            var userId = User.Identity.GetUserId<int>();
            var cart = Session[Constants.CartSessionKey] as CartViewModel;
            if (cart == null)
            {
                cart = cartService.CreateCart(Session.SessionID, userId);
            }
            else if (userId != 0 && !cart.IsPersistent)
            {
                cart = cartService.CreateCartAfterLogin(cart, Session.SessionID, userId);
            }

            Session[Constants.CartSessionKey] = cart;

            return cart;
        }
        #endregion
    }
}

Shop.Web/Controllers/OrderController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Shop.Common.Facade;
using Shop.Domain.Entities.Shop;
using Shop.ServicesFacade.Base;
using Shop.ViewModel.Shop;

namespace Shop.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IService<Order> orderService;
        private readonly IMapper mapper;

        public OrderController(IService<Order> orderService, IMapper mapper)
        {
            this.orderService = orderService;
            this.mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var entities = await orderService.GetAllAsync();
            var model = mapper.Map<IList<OrderViewModel>>(entities);
            return View(model);
        }
    }
}

Shop.Web/Controllers/ProductCategoryController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Shop.Common.Facade;
using Shop.Domain.Entities.Shop;
using Shop.ServicesFacade.Base;
using Shop.ViewModel.Shop;

namespace Shop.Web.Controllers
{
    [Authorize]
    public class ProductCategoryController : Controller
    {
        private readonly IService<ProductCategory> productCategoryService;
        private readonly IMapper mapper;

        public ProductCategoryController(IService<ProductCategory> productCategoryService, IMapper mapper)
        {
            this.productCategoryService = productCategoryService;
            this.mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var entities = await productCategoryService.GetAllAsync();
            var model = mapper.Map<IList<ProductCategoryViewModel>>(entities);
            return View(model);
        }

        public async Task<ActionResult> Details(int id)
        {
            var productCategory = await productCategoryService.GetAsync(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            var model = mapper.Map<ProductCategoryViewModel>(productCategory);
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = mapper.Map<ProductCategory>(model);
                await productCategoryService.CreateAsync(entity);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var productCategory = await productCategoryService.GetAsync(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            var model = mapper.Map<ProductCategoryViewModel>(productCategory);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = mapper.Map<ProductCategory>(model);
                await productCategoryService.UpdateAsync(entity);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<ActionResult> Delete(int id)
        {
            var productCategory = await productCategoryService.GetAsync(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            var model = mapper.Map<ProductCategoryViewModel>(productCategory);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await productCategoryService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Shop.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Shop.Common.Facade;
using Shop.Domain.Entities.Shop;
using Shop.ServicesFacade.Base;
using Shop.ViewModel.Shop;

namespace Shop.Web.Controllers
{
    public class ProductController : Controller
    {
        private static readonly string PhotosBaseUrl = ConfigurationManager.AppSettings["PhotosBaseUrl"];

        private readonly IService<Product> productService;
        private readonly IService<ProductCategory> productCategoryService;
        private readonly IMapper mapper;

        public ProductController(IService<Product> productService, IService<ProductCategory> productCategoryService, IMapper mapper)
        {
            this.productService = productService;
            this.productCategoryService = productCategoryService;
            this.mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var entities = await productService.GetAllAsync();
            var model = mapper.Map<IList<ProductViewModel>>(entities);
            return View(model);
        }

        public async Task<ActionResult> Details(int id)
        {
            var product = await productService.GetAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            var model = mapper.Map<ProductViewModel>(product);
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> Create()
        {
            ViewBag.CategoryId = new SelectList(await productCategoryService.GetAllAsync(), "Id", "Title");
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductViewModel model, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                model.PhotoUrl = GetPhotoUrl(photo);

                var entity = mapper.Map<Product>(model);
                await productService.CreateAsync(entity);
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(await productCategoryService.GetAllAsync(), "Id", "Title", model.CategoryId);
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            var product = await productService.GetAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            ViewBag.CategoryId = new SelectList(await productCategoryService.GetAllAsync(), "Id", "Title", product.CategoryId);
            var model = mapper.Map<ProductViewModel>(product);
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductViewModel model, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                model.PhotoUrl = GetPhotoUrl(photo);

                var entity = mapper.Map<Product>(model);
                await productService.UpdateAsync(entity);
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(await productCategoryService.GetAllAsync(), "Id", "Title", model.CategoryId);
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            var product = await productService.GetAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            var model = mapper.Map<ProductViewModel>(product);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await productService.DeleteAsync(id);
            return RedirectToAction("Index");
        }

        #region Private methods
        private string GetPhotoUrl(HttpPostedFileBase photo)
        {
            var photoUrl = string.Empty;
            if (photo != null)
            {
                var photosDirectory = Server.MapPath(PhotosBaseUrl);
                if (!Directory.Exists(photosDirectory))
                {
                    Directory.CreateDirectory(photosDirectory);
                }

                var extension = Path.GetExtension(photo.FileName);
                photoUrl = string.Format("{0}/{1}{2}", PhotosBaseUrl, Guid.NewGuid(), extension);
                var filePath = Server.MapPath(photoUrl);
                photo.SaveAs(filePath);
            }

            return photoUrl;
        }
        #endregion
    }
}

Shop.Web/Views/Shared/_Cart.cshtml
@using Shop.ViewModel.Shop
@model CartViewModel

@if (Model == null || !Model.Items.Any())
{
    return;
}

<div class="cart">
    @foreach (var item in Model.Items)
    {
        <div>
            <span>@string.Format("Product: {0}. Price: {1}. Amount: {2}. Subtotal: {3}", item.Title, item.Price, item.Amount, item.Price * item.Amount)</span>
            @using (Ajax.BeginForm("DeleteItem", "Cart", new { item.ProductId }, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "location.reload()",
                OnFailure = "alert('Error')"
            }))
            {
                @Html.AntiForgeryToken()
            
                <input type="submit" value="Delete from cart" class="btn btn-default" />
            }
        </div>
    }

    <div class="clearfix actions">
        <div class="pull-left">
            @using (Ajax.BeginForm("Empty", "Cart", new AjaxOptions
        {
            HttpMethod = "POST",
            OnSuccess = "location.reload()",
            OnFailure = "alert('Error')"
        }))
            {
                @Html.AntiForgeryToken()

                <input type="submit" value="Empty cart" class="btn btn-default" />
            }
        </div>
        <div class="pull-right">
            @Html.ActionLink("Checkout", "Index", "Checkout", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>

Shop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace","Ajax"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"2aea3c18-776f-4081-bad6-fca5bebdddcd"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Categories", "Index", "ProductCategory")</li>
                        <li>@Html.ActionLink("Orders", "Index", "Order")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Action("Get", "Cart")
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - Shop</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>